create table public.clients (
    id integer generated by default as identity not null,
    client_name varchar(100) null,
    client_age int not null check(client_age < 100 and client_age > 0),
    email varchar(255) not null,
    constraint clients_pk primary key (id),
    constraint clients_unique unique (email)
);

create table public.agents (
    id integer generated by default as identity not null,
    agent_name varchar(100) null,
    email varchar(255) not null,
    constraint agents_pk primary key (id),
    constraint agents_unique unique (email)
);

create table public.knowledge_base (
    id integer generated by default as identity not null,
    title varchar(255) null,
    knowledge_base_content text null,
    created_at timestamp default CURRENT_TIMESTAMP null,
    constraint knowledge_base_pkey primary key (id)
);


create table public.tickets (
    id integer generated by default as identity not null,
    title varchar(255) null,
    description text null,
    client_id integer not null,
    agent_id integer null,
    status varchar(10) not null check(status in ('открыт', 'в работе', 'решен', 'закрыт')),
    created_at timestamp default now() not null,

    constraint tickets_pk primary key(id),
    constraint tickets_agents_fk foreign key(agent_id) references public.agents(id),
    constraint tickets_clients_fk foreign key(client_id) references public.clients(id)
);

create table public.knowledge_for_ticket (
    ticket_id integer,
    knowledge_id integer,
    constraint knowledge_for_ticket_pk primary key(ticket_id, knowledge_id),
    constraint knowledge_for_ticket_ticket_id_fk foreign key(ticket_id) references public.tickets(id),
    constraint knowledge_for_ticket_knowledge_id_fk foreign key(knowledge_id) references public.knowledge_base(id)
);


